---
title: "Bienvenidos al sitio web de Estudios"
---

---

<style>
.twitterborder {
    height:300px;
    margin-top:3px;
    margin-right:5%;
    float:right;
    background:#707070;
    text-align:center;
}
</style>

<div class="twitterborder">
<a class="twitter-timeline tw-align-right" data-widget-id="591646755353186304"  width="250px" href="https://twitter.com/LC_Decom?ref_src=twsrc%5Etfw">Tweets by @LC_Decom</a> 

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
</script>

</div>


<p align="justify"><font size=3>Aquí econtrarás estudios, documentos de análisis e información que esperamos contribuyan al diseño, ejecución y evaluación de las políticas sociales de DECOM. El propósito de este sitio es que los distintos equipos ejecutantes de los programas de la dirección, cuenten con un acceso rápido, fácil y amigable a la información social disponible, de esta manera esperamos ser un soporte para la toma de decisiones.</p>

<p align="justify"><font size=3>En la barra de navegación ubicada en la parte superior, encontrarás los repositorios de <a href="https://estudiosdecom.github.io/EstudiosDecom.git.io/doc_analisis.html"> análisis</a> y el acceso a nuestro <a href="https://estudiosdecom.github.io/EstudiosDecom.git.io/maps.html">portal de infraestructura de datos espaciales (IDE DECOM)</a> que contienen documentos de análisis e información geoespacial dispuesta par. También, hallarás el <a href="https://estudiosdecom.github.io/EstudiosDecom.git.io/diagnostico.html"> diagnóstico social comunal</a> elaborado el 2019 por el equipo, y que actualiza el documento del año 2015. En él se dispone de análisis e información estadística proveniente principalmente de los microdatos del Censo 2017, la Encuesta de Caracterización Socioeconómica (CASEN), y el Sistema de Indicadores y Estándares del Desarrollo Urbano (SIEDU).</p> 


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</br>