---
title: "Nueva estrategia social DECOM"
---

---

<p style="font-size:18px"><b>Resumen</b></p>

<p align="justify">La nueva estrategia de desarrollo social de DECOM, está enmarcada en un proceso de modernización en la gestión de los programas ejecutados por la Dirección, e impulsada por la necesidad de brindar protección a los vecinos y vecinas de Las Condes, afectados por la emergencia sanitaria y crisis económica en el contexto de pandemia por la enfermedad de COVID-19</p>

<p align="justify">La base de este proceso se encuentra en la definición de un modelo brechas de bienestar, que se inspira en la la metodología de pobreza multidimensional de Alkire & Foster (2011). El modelo evalúa una cantidad definida de dimensiones asociadas a un concepto amplio de bienestar social, en las cuales los hogares presentan carencias (vulnerabilidades).</p>

<p align="justify">El concepto de bienestar que aquí se utiliza, se desprende del enfoque de capacidades de Amartya Sen[^1], cuyas reflexiones respecto al desarrollo humano, han puesto el foco del bienestar en las personas, la protección de sus funciones y la ampliación de sus capacidades para perseguir aquellos resultados que por diversas razones valoran para sus vidas.</p>

<p align="justify">En cuanto al proceso de trabajo, éste se estructuró en seis etapas de desarrollo paralelas, cada una con hitos y productos entregables; (i) revisión del modelo actual de asignación de beneficios y sus instrumentos de focalización; (ii) construcción del modelo de brechas DECOM; (iii) operacionalización de variables e instrumentos de medición; (iv) identificación de los componentes de programas 2020 y validación de estos en el sistema informático; (v) aplicación del instrumento piloto y eventuales ajustes; (vi) diseño e incorporación de estrategias de transferencias condicionadas.</p>



[^1]: Ver https://www.ophi.org.uk/wp-content/uploads/OPHIWP094.pdf



